### ISSUE TITLE
Enhancement: Ghostwriter profile

### ISSUE THREAD

**Issue by domwhewell-sage** [t94j0/gophish-notifier#5]
Hi, would it be possible to create a profile for inserting logs into ghostwriter's oplog https://github.com/GhostManager/Ghostwriter

Ghostwriter has a [graphql api](https://www.ghostwriter.wiki/features/graphql-api) which should be able to ingest data from this.

I can open a PR for it if community contributions are accepted :)

**Comment by domwhewell-sage** [comment]
Thanks it'll give me a chance to brush up on my golang!

**Comment by t94j0** [comment]
Thanks for the contribution!
